In [1]:
import numpy as np

In [2]:
matrix = [[0,1,2],[3,4,5],[6,7,8]]
nd_array=np.array(matrix)

In [3]:
nd_array[0:1]


array([[0, 1, 2]])

In [4]:
b = np.array([1, 2, 3, 4, 5], dtype=float)

In [5]:
b

array([1., 2., 3., 4., 5.])

In [6]:
np.arange(1, 2, 0.3, dtype=float)

array([1. , 1.3, 1.6, 1.9])

In [7]:
np.array([False, False, True])

array([False, False,  True])

In [8]:
a = np.array([0, -1, 11])
b = np.array([3, 7, 2])

In [9]:
a*b

array([ 0, -7, 22])

In [10]:
b.dot(a)

15

In [11]:
np.dot(a, b)

15

In [12]:
np.dot(a, b) / np.linalg.norm(a) / np.linalg.norm(b)

0.1724707686818527

In [13]:
c = np.array([8, 10, -1, 0, 0])

In [14]:
c

array([ 8, 10, -1,  0,  0])

In [15]:
c.reshape((5, 1))

array([[ 8],
       [10],
       [-1],
       [ 0],
       [ 0]])

In [16]:
c[np.newaxis, :]

array([[ 8, 10, -1,  0,  0]])

In [17]:
c[:, np.newaxis]

array([[ 8],
       [10],
       [-1],
       [ 0],
       [ 0]])

In [18]:
c.reshape((1, 5))

array([[ 8, 10, -1,  0,  0]])

In [19]:
np.array([False, False, True])

array([False, False,  True])

In [20]:
import numpy as np

In [21]:
np.eye((4, 5))

TypeError: 'tuple' object cannot be interpreted as an index

In [22]:
np.ones((10, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [23]:
np.array([4, 3, 2], [2, 9, 1], [3, 1, 9])

ValueError: only 2 non-keyword arguments accepted

In [24]:
np.eye(2, 3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [25]:
np.arange(1, 13, 2).reshape((3, 2))

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [26]:
a = np.eye(4, 5)

In [27]:
a


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [28]:
a[[0, 3], [1, 3]]

array([0., 1.])